cache:
   untracked: true
   key: ${CI_BUILD_REF_NAME}
   paths:
     - ./node_modules/
     
stages:
  - build_upload
  - upload
 
build_dist:
  stage: build_upload
  script:
    - export NODE_HOME=/nodejs
    - export PATH=$PATH:$NODE_HOME/bin 
    - export NODE_PATH=$NODE_HOME/lib/node_modules
    - npm install
    - npm audit fix
    - npm run build
    - ls
    - export AWS_CREDENTIAL_FILE=/home/gitlab-runner/.aws/crendentials
    - export AWS_CONFIG_FILE=/home/gitlab-runner/.aws/config
    - aws --endpoint=http://pub1-bjyt.s3.360.cn s3 sync ./dist s3://s3-yzt-front/${CI_BUILD_REF_NAME}/situation

  only:
    - test-s3
    - develop
    - master